### ISSUE TITLE
Github Project Description link is Dead

### ISSUE THREAD

**Issue by srwaggon** [arcfide/ChezWEB#16]
The project description at the top of the GitHub page at https://github.com/arcfide/ChezWEB contains a link (http://www.sacrideo.us/v5/proj/chezweb/).

That link is dead.

RIP

**Comment by arcfide** [comment]
Fixed in 3940384 . Thanks for the report. It's unfortunate, but I don't have a maintained website for ChezWEB right now, and you mostly should build from source. :-)
