### ISSUE TITLE
MetaPost on Ubuntu

### ISSUE THREAD

**Issue by arcfide** [arcfide/ChezWEB#3]
For some reason, the meta post installation with Ubuntu doesn't seem to be working very well. It gives a strange error about not being able to find the mem files.

    kpathsea: Running mktexfmt mpost.mem

    Sorry, I can't find the 'mpost' mem file; will try 'plain'.
    kpathsea: Running mktexfmt plain.mem

    I can't find the 'plain' mem file!

**Comment by gwatt** [comment]
At least on Debian, the mpost binary is distributed in the `texlive-binaries` package while the supplementary files are in `texlive-metapost`
